version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=tbriggs
    volumes:
      - ~/postgres-data/blog:/var/lib/postgresql/data
    ports:
      - '5436:5432'

  app:
    build: .
    ports:
      - "5002:5000"